services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jundoldb
          property: connectionString

  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10001"
    plan: free

  - type: cron
    name: keepalive-pinger
    env: python
    schedule: "*/5 * * * *"
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/keepalive.py"
    plan: free
